### ISSUE TITLE
AFP Test Application throws unhandled exception

### ISSUE THREAD

**Issue by RWELabs** [RyanWalpoleEnterprises/RyTek3-AFP#1]
Post application framework patch throws an unhandled exception when trying to access the test application to verify the success or failure of the patching procedure.

**Comment by RyanWalpole** [comment]
Unhandled exception is caused by an issue wherein the demo application was (for some reason) not included in the built and compiled installer script (the script was updated, but the updated script was not used to generate the installer?).
Pushing update 1.0.2 (200801) to fix the issue.
